site_name: Сайт-портфолио Артура Петровича

nav:
  - 'Главная': index.md
  - 'Обо мне': author.md
  - 'Сотрудничество': cooperate.md
  - 'Лабораторные работы':
    - 'Все работы': labworks.md
    - 'Лабораторная работа 5': labwork5.md
    - 'Лабораторная работа 6': labwork6.md
    - 'Лабораторная работа 7': labwork7.md


theme:
  name: material